version: 0.2
env:
  exported-variables:
    - DBP_API_KEY
    - BASE_API_ROUTE
    - BUGSNAG_API_KEY
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing nvm…"
      - curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
      - . ~/.nvm/nvm.sh
      - nvm install 22
      - nvm use 22
      - node --version   # ⇒ v22.x
      - npm --version
      - npm install
  pre_build:
    commands:
      - npm run lint
  build:
    commands:
      - npm run build
artifacts:
  files:
    - .next/**/*
    - public/**/*
    - internals/scripts/**/*
    - scripts/**/*
    - nextServer.js
    - ecosystem.config.js
    - package.json
    - next.config.js
    - newrelic.js
    - appspec.yml
    - env-config.js
    - .babelrc.js
    - .gitignore
    - node_modules/**/*
    - app/utils/checkBookName.js
    - app/utils/bugsnagServer.js
    - app/utils/isoOneToThree.json
    - app/utils/bookNameToId.json
    - app/utils/osisIdMap.json
  discard-paths: no
  name: 'BibleIsWebsite-$CODEBUILD_BUILD_NUMBER'
