version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  pre_build:
    commands:
      - npm run lint
  build:
    commands:
      - npm run build
artifacts:
  files:
    - .next/**/*
    - public/**/*
    - internals/scripts/**/*
    - scripts/**/*
    - nextServer.js
    - ecosystem.config.js
    - package.json
    - next.config.js
    - newrelic.js
    - appspec.yml
    - env-config.js
    - .babelrc.js
    - .gitignore
    - node_modules/**
    - app/utils/checkBookName.js
    - app/utils/bugsnagServer.js
    - app/utils/isoOneToThree.json
    - app/utils/bookNameToId.json
    - app/utils/osisIdMap.json
  discard-paths: no
  name: 'BibleIsWebsite-$CODEBUILD_BUILD_NUMBER'
