version: 0.2

runas: ubuntu

env:
  exported-variables:
    - DBP_API_KEY
    - BASE_API_ROUTE
    - BUGSNAG_API_KEY

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - BUILD_ID=$(git rev-parse HEAD) NODE_ENV=production npm run build
artifacts:
  files:
    - .next/**/*
    - public/**/*
    - internals/scripts/**/*
    - scripts/**/*
    - nextServer.js
    - ecosystem.config.js
    - package.json
    - next.config.js
    - newrelic.js
    - appspec.yml
    - env-config.js
    - .babelrc.js
    - .gitignore
    - node_modules/**/*
    - app/utils/checkBookName.js
    - app/utils/bugsnagServer.js
    - app/utils/isoOneToThree.json
    - app/utils/bookNameToId.json
    - app/utils/osisIdMap.json
  name: $(AWS_REGION)-$(date +%Y-%m-%d)
