version: 0.2
env:
  exported-variables:
    - DBP_API_KEY
    - BASE_API_ROUTE
    - BUGSNAG_API_KEY
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install
  pre_build:
    commands:
      - npm run lint
  build:
    commands:
      - npm run build
artifacts:
  files:
    - .next/**/*
    - public/**/*
    - internals/scripts/**/*
    - scripts/**/*
    - nextServer.js
    - ecosystem.config.js
    - package.json
    - next.config.js
    - appspec.yml
    - .gitignore
    - node_modules/**/*
    - app/utils/checkBookName.js
    - app/utils/bugsnagServer.js
    - app/utils/isoOneToThree.json
    - app/utils/bookNameToId.json
    - app/utils/osisIdMap.json
    - app/utils/parseM3U8.js
    - app/utils/serverCachedFetch.js
    - app/utils/apiEndpointConfig.js
    - app/utils/retryableRequest.js
    - app/utils/environmentConfig.js
    - app/utils/rtlDetection.js
  discard-paths: no
  name: 'BibleIsWebsite-$CODEBUILD_BUILD_NUMBER'
