services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    # Load ALL vars from .env in this folder
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-3011}:3000"
    # Bind-mount your source tree for two-way sync,
    # but isolate build artifacts and deps in named volumes
    volumes:
      - ./:/usr/src/app:cached          # your source code
      - next_build:/usr/src/app/.next   # production build output
      - deps:/usr/src/app/node_modules  # npm dependencies
    restart: "no"
volumes:
  next_build: {}
  deps: {}
